export const Titles: any = {
    '/': 'Моя страница',
    '/profile': 'Мой профиль',
    '/groups': 'Группы',
    '/homework': 'Домашнее задание',
    '/homework/create': 'Создать домашнее задание',
    '/training': 'Тренировка',
    '/olympiads': 'Олимпиада',
    '/olympiad': 'Олимпиада',
    '/olympiad/history': 'Прошедшие олимпиады',
    '/olympiad/create': 'Создать олимпиаду',
    '/settings': 'Настройки',

    '/centers': 'Центры',
    '/centers/statistic': 'Статистика',
    '/centers/create': 'Создать центр',

    '/directors': 'Директора',

    '/franchises': 'Франшизы',
    '/franchises/statistic': 'Статистика Франшиз',

    // Упражнения
    '/training/1/1': 'Анзан (+ -)',
    '/training/1/2': 'Листы (+ -)',
    '/training/1/3': 'Анзан (× ÷)',
    '/training/1/4': 'Листы (× ÷)',
    '/training/1/5': 'Двойной анзан',
    '/training/1/6': 'Флеш-Анзан',
    '/training/1/17': 'Спец-Анзан',
    '/training/1/18': 'Зеркальный-Анзан',
    '/training/1/21': 'Мульти-Анзан',
    '/training/1/22': 'Прогрессия',
    '/training/2/7': 'Список слов',
    '/training/2/8': 'Личности',
    '/training/2/9': 'Страны',
    '/training/2/10': 'Цифровой ряд',
    '/training/2/11': 'Главная система',
    '/training/2/12': 'Цифра-Звук',
    '/training/2/13': 'Цифра-Образ',
    '/training/2/14': 'Какой день недели?',
    '/training/2/15': 'Список слов (Листы)',
    '/training/2/16': 'Числа (Листы)',
    '/training/2/19': 'Цифра-Картинка',
    '/training/1/23': 'Анзан',
    '/training/1/24': 'Лист',

    // Упражнения
    '/training/1/1/setting': 'Настройка Анзан (+ -)',
    '/training/1/2/setting': 'Настройка Листы (+ -)',
    '/training/1/3/setting': 'Настройка Анзан (× ÷)',
    '/training/1/4/setting': 'Настройка Листы (× ÷)',
    '/training/1/5/setting': 'Настройка Двойной анзан',
    '/training/1/6/setting': 'Настройка Флеш-Анзан',
    '/training/1/17/setting': 'Настройка Спец-Анзан',
    '/training/1/18/setting': 'Настройка Зеркальный-Анзан',
    '/training/1/21/setting': 'Настройка Мульти-Анзан',
    '/training/1/22/setting': 'Настройка Прогрессия',
    '/training/2/7/setting': 'Настройка Список слов',
    '/training/2/8/setting': 'Настройка Личности',
    '/training/2/9/setting': 'Настройка Страны',
    '/training/2/10/setting': 'Настройка Цифровой ряд',
    '/training/2/11/setting': 'Настройка Главная система',
    '/training/2/12/setting': 'Настройка Цифра-Звук',
    '/training/2/13/setting': 'Настройка Цифра-Образ',
    '/training/2/14/setting': 'Настройка Какой день недели?',
    '/training/2/15/setting': 'Настройка Список слов (Листы)',
    '/training/2/16/setting': 'Настройка Числа (Листы)',
    '/training/2/19/setting': 'Настройка Цифра-Картинка',
    '/training/1/23/setting': 'Настройка Анзан',
    '/training/1/24/setting': 'Настройка Листы',

    '/settings/franchise': 'Настройка Франшизы',
    '/settings/formul-title': 'Название формул',
    '/settings/task-title': 'Название упражнений',
    '/settings/categories': 'Категории',
    '/settings/cities': 'Города',

    '/settings/prices': 'Цены',
    '/settings/payments': 'Оплата',

    '/tasks/countries': 'Страны',
    '/tasks/personalities': 'Личности',
    '/tasks/words': 'Слова',
    '/tasks/digital-picture': 'Цифра-Картинка',
    '/tasks/word-numbers': 'Главная система',


    '/settings/custom-algorithms': 'Алгоритмы',
    '/settings/custom-algorithms/create': 'Добавить алгоритмы',

    '/settings/custom-exercises': 'Свои примеры',
    '/settings/custom-exercises/create': 'Создать примеры',
    '/platform': 'Об платформе',
};
